name: celeryviz_frontend_core
description: This is the core UI library for the CeleryViz project
version: 0.0.7
homepage: https://github.com/bhavya-tech/celeryviz
repository: https://github.com/bhavya-tech/celeryviz_frontend_core
issue_tracker: https://github.com/bhavya-tech/celeryviz_frontend_core/issues


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1
  flutter_bloc: ^9.1.1
  socket_io_client: ^3.1.4
  bloc: ^9.2.0
  equatable: ^2.0.5
  intl: ^0.20.2
  freezed: ^3.2.5
  ndjson: ^0.2.2
  google_fonts: ^8.0.2
  ffi: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

screenshots:
  - description: 'Parallel tasks with different log levels'
    path: screenshots/parallel_tasks_log_levels.jpeg
  - description: 'Recursively spawning the same task'
    path: screenshots/recursive_task_spawn.jpeg
  - description: 'Spawning multiple subtasks'
    path: screenshots/spawning_subtasks.jpeg

topics:
  - debugging
  - celeryviz
  - visualization
  - monitoring