name: celeryviz_frontend_core
description: This is the core UI library for the CeleryViz project
version: 0.0.4
homepage: https://github.com/bhavya-tech/celeryviz
repository: https://github.com/bhavya-tech/celeryviz_frontend_core
issue_tracker: https://github.com/bhavya-tech/celeryviz_frontend_core/issues


environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1
  flutter_bloc: ^8.1.2
  socket_io_client: ^2.0.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  logger: ^1.3.0
  intl: ^0.18.1
  freezed: ^2.3.4
  ndjson: ^0.2.2
  google_fonts: ^5.1.0
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

screenshots:
  - path: screenshots/Parallel tasks with different log levels.jpeg
    description: Multiple tasks running in parallel showing different log levels
  - path: screenshots/Resursively spawning the same task.jpeg
    description: A task spawning multiple instances of itself
  - path: screenshots/Spawning multiple subtasks.jpeg
    description: Multiple sub-tasks spawning from a single task

topics:
  - debugging
  - celeryviz
  - visualization
  - monitoring