name: Dispatch on Pub Dev Publish

on:
  workflow_run:
    workflows: ["publish_to_pub_dev.yml"]
    types: [completed]
  workflow_dispatch:

jobs:
  trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger celeryviz_with_lib release workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: bhavya-tech/celeryviz_with_lib
          token: ${{ secrets.PAT }}
          event-type: release-published
          client-payload: '{"tag": "${{ github.ref_name }}"}'
  
      - name: Trigger celeryviz_demo release workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: bhavya-tech/celeryviz_demo
          token: ${{ secrets.PAT }}
          event-type: release-published